/**
 * Generates the OCI CLI export bash script.
 *
 * Used by both the REST endpoint (GET /api/export-script) and
 * the GraphQL `exportScript` query.
 */
export function generateExportScript(): string {
  return `#!/usr/bin/env bash
# OCI Resource Export Script - Generated by OCI Visualizer
# Usage:
#   ./oci-export.sh -c <compartment-ocid> [-r region] [-o output-dir]
#   ./oci-export.sh -f <file-with-compartment-ocids> [-r region] [-o output-dir]
set -euo pipefail

CID="" FILE="" REGION="" OUTPUT_DIR="oci-export-\$(date +%Y%m%d-%H%M%S)"
while getopts "c:f:r:o:h" opt; do
  case \$opt in
    c) CID="\$OPTARG";;  f) FILE="\$OPTARG";;
    r) REGION="\$OPTARG";; o) OUTPUT_DIR="\$OPTARG";;
    h) echo "Usage: \$0 [-c OCID] [-f FILE] [-r REGION] [-o DIR]"; exit 0;;
    *) exit 1;;
  esac
done

CIDS=()
if [ -n "\$FILE" ]; then
  while IFS= read -r l || [ -n "\$l" ]; do l=\$(echo "\$l"|xargs); [ -z "\$l" ]||[[ "\$l"==\\#* ]]||CIDS+=("\$l"); done < "\$FILE"
elif [ -n "\$CID" ]; then CIDS=("\$CID")
else CID=\$(oci iam compartment list --query 'data[0]."compartment-id"' --raw-output 2>/dev/null||true)
  [ -z "\$CID" ] && { echo "ERROR: specify -c or -f"; exit 1; }; CIDS=("\$CID"); fi

RF=""; [ -n "\$REGION" ] && RF="--region \$REGION"
mkdir -p "\$OUTPUT_DIR"
echo "=== OCI Export (\${#CIDS[@]} compartments) ==="

# merge_parts: combine per-chunk JSON array files into one {"data":[...]} output
# Usage: merge_parts <tmp_dir> <output_file>
merge_parts() {
  local td=\$1 o=\$2
  local parts=("\$td"/part_*.json)
  if [ ! -e "\${parts[0]}" ]; then return 1; fi
  jq -s 'add' "\$td"/part_*.json | jq '{data:.}' >"\$o" 2>/dev/null
  # Verify output has data (jq on empty files exits 0 with no output so check -s first)
  [ -s "\$o" ] && jq -e '.data and (.data|length) > 0' "\$o" >/dev/null 2>&1 && return 0 || { rm -f "\$o"; return 1; }
}

e() {
  local n=\$1 c=\$2; local o="\$OUTPUT_DIR/\$n.json"; echo -n "  \$n..."
  if [ \${#CIDS[@]} -eq 1 ]; then
    eval "\$c --compartment-id \${CIDS[0]} --all \$RF" >"\$o" 2>/dev/null && echo " OK" || { echo " skip"; rm -f "\$o"; }
  else
    local td; td=\$(mktemp -d); local i=0
    for cid in "\${CIDS[@]}"; do
      eval "\$c --compartment-id \$cid --all \$RF" 2>/dev/null | jq '.data//[]' >"\$td/part_\$i.json" 2>/dev/null || true
      # Remove empty arrays to save disk
      jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
      i=\$((i+1))
    done
    merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
    rm -rf "\$td"
  fi
}

ead() {
  local n=\$1 c=\$2; local o="\$OUTPUT_DIR/\$n.json"; echo -n "  \$n (per-AD)..."
  local td; td=\$(mktemp -d); local i=0
  for cid in "\${CIDS[@]}"; do
    local ads; ads=\$(oci iam availability-domain list --compartment-id "\$cid" \$RF 2>/dev/null|jq -r '.data[]?.name//empty' 2>/dev/null||true)
    [ -z "\$ads" ] && continue
    while IFS= read -r ad; do [ -z "\$ad" ]&&continue
      eval "\$c --compartment-id \$cid --availability-domain \\"\$ad\\" --all \$RF" 2>/dev/null | jq '.data//[]' >"\$td/part_\$i.json" 2>/dev/null || true
      jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
      i=\$((i+1))
    done <<<"\$ads"
  done
  merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
  rm -rf "\$td"
}

epp() {
  local n=\$1 c=\$2 pf=\$3 pk=\$4; local o="\$OUTPUT_DIR/\$n.json" pp="\$OUTPUT_DIR/\$pf.json"; echo -n "  \$n (per-parent)..."
  [ ! -f "\$pp" ] && { echo " skip (no \$pf)"; return; }
  local pids; pids=\$(jq -r ".data[]?\$pk//empty" "\$pp" 2>/dev/null||true)
  [ -z "\$pids" ] && { echo " empty"; return; }
  local td; td=\$(mktemp -d); local i=0
  while IFS= read -r pid; do [ -z "\$pid" ]&&continue
    eval "\$c \$pid --all \$RF" 2>/dev/null | jq '.data//[]' >"\$td/part_\$i.json" 2>/dev/null || true
    jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
    i=\$((i+1))
  done <<<"\$pids"
  merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
  rm -rf "\$td"
}

echo "=== IAM ==="
e compartments "oci iam compartment list --compartment-id-in-subtree true"
e users "oci iam user list"
e groups "oci iam group list"
e policies "oci iam policy list"
e dynamic-groups "oci iam dynamic-group list"
epp api-keys "oci iam user api-key list --user-id" users '.id'
epp customer-secret-keys "oci iam customer-secret-key list --user-id" users '.id'

echo "=== Compute ==="
e instances "oci compute instance list"
e images "oci compute image list"
e vnic-attachments "oci compute vnic-attachment list"
ead boot-volume-attachments "oci compute boot-volume-attachment list"
e instance-configurations "oci compute-management instance-configuration list"

echo "=== Network ==="
e vcns "oci network vcn list"
e subnets "oci network subnet list"
e security-lists "oci network security-list list"
e route-tables "oci network route-table list"
e nsgs "oci network nsg list"
e internet-gateways "oci network internet-gateway list"
e nat-gateways "oci network nat-gateway list"
e service-gateways "oci network service-gateway list"
e drgs "oci network drg list"
e drg-attachments "oci network drg-attachment list"
e local-peering-gateways "oci network local-peering-gateway list"
e dhcp-options "oci network dhcp-options list"

echo "=== Storage ==="
e block-volumes "oci bv volume list"
ead boot-volumes "oci bv boot-volume list"
e volume-backups "oci bv backup list"
e volume-groups "oci bv volume-group list"
ead file-systems "oci fs file-system list"
e buckets "oci os bucket list"

echo "=== Database ==="
e db-systems "oci db system list"
e autonomous-databases "oci db autonomous-database list"
e mysql-db-systems "oci mysql db-system list"
e db-homes "oci db db-home list"

echo "=== Load Balancer ==="
e load-balancers "oci lb load-balancer list"
e network-load-balancers "oci nlb network-load-balancer list"

echo "=== Containers ==="
e oke-clusters "oci ce cluster list"
epp node-pools "oci ce node-pool list --cluster-id" oke-clusters '.id'
e container-instances "oci container-instances container-instance list"
e container-repos "oci artifacts container-repository list"
e container-images "oci artifacts container-image list"
e image-signatures "oci artifacts container image-signature list"

echo "=== Serverless ==="
e functions-applications "oci fn application list"
epp functions "oci fn function list --application-id" functions-applications '.id'
e api-gateways "oci api-gateway gateway list"
epp api-deployments "oci api-gateway deployment list --gateway-id" api-gateways '.id'

echo "=== Security ==="
e vaults "oci kms management vault list"
e secrets "oci vault secret list"
e container-scan-results "oci vulnerability-scanning container-scan-result list"

echo "=== Observability ==="
e log-groups "oci logging log-group list"
epp logs "oci logging log list --log-group-id" log-groups '.id'

echo "=== DNS ==="
e dns-zones "oci dns zone list"

echo ""
echo "Done! ZIP and upload: cd \$OUTPUT_DIR && zip -r ../oci-export.zip *.json"
`;
}
