/**
 * Generates the OCI CLI export bash script.
 *
 * Used by both the REST endpoint (GET /api/export-script) and
 * the GraphQL `exportScript` query.
 */
export function generateExportScript(): string {
  return `#!/usr/bin/env bash
# OCI Resource Export Script - Generated by OCI Visualizer
# Usage:
#   ./oci-export.sh -c <compartment-ocid> [-r region] [-o output-dir]
#   ./oci-export.sh -f <file-with-compartment-ocids> [-r region] [-o output-dir]
set -euo pipefail

CID="" FILE="" REGION="" OUTPUT_DIR="oci-export-\$(date +%Y%m%d-%H%M%S)"
while getopts "c:f:r:o:h" opt; do
  case \$opt in
    c) CID="\$OPTARG";;  f) FILE="\$OPTARG";;
    r) REGION="\$OPTARG";; o) OUTPUT_DIR="\$OPTARG";;
    h) echo "Usage: \$0 [-c OCID] [-f FILE] [-r REGION] [-o DIR]"; exit 0;;
    *) exit 1;;
  esac
done

CIDS=()
if [ -n "\$FILE" ]; then
  while IFS= read -r l || [ -n "\$l" ]; do l=\$(echo "\$l"|xargs); [ -z "\$l" ]||[[ "\$l"==\\#* ]]||CIDS+=("\$l"); done < "\$FILE"
elif [ -n "\$CID" ]; then CIDS=("\$CID")
else CID=\$(oci iam compartment list --query 'data[0]."compartment-id"' --raw-output 2>/dev/null||true)
  [ -z "\$CID" ] && { echo "ERROR: specify -c or -f"; exit 1; }; CIDS=("\$CID"); fi

RF=""; [ -n "\$REGION" ] && RF="--region \$REGION"
mkdir -p "\$OUTPUT_DIR"
echo "=== OCI Export (\${#CIDS[@]} compartments) ==="

# merge_parts: combine per-chunk JSON array files into one {"data":[...]} output
# Usage: merge_parts <tmp_dir> <output_file>
merge_parts() {
  local td=\$1 o=\$2
  local parts=("\$td"/part_*.json)
  if [ ! -e "\${parts[0]}" ]; then return 1; fi
  jq -s 'add' "\$td"/part_*.json | jq '{data:.}' >"\$o" 2>/dev/null
  # Verify output has data (jq on empty files exits 0 with no output so check -s first)
  [ -s "\$o" ] && jq -e '.data and (.data|length) > 0' "\$o" >/dev/null 2>&1 && return 0 || { rm -f "\$o"; return 1; }
}

e() {
  local n=\$1 c=\$2; local o="\$OUTPUT_DIR/\$n.json"; echo -n "  \$n..."
  if [ \${#CIDS[@]} -eq 1 ]; then
    eval "\$c --compartment-id \${CIDS[0]} --all \$RF" >"\$o" 2>/dev/null && echo " OK" || { echo " skip"; rm -f "\$o"; }
  else
    local td; td=\$(mktemp -d); local i=0
    for cid in "\${CIDS[@]}"; do
      eval "\$c --compartment-id \$cid --all \$RF" 2>/dev/null | jq '.data | if type=="array" then . else (.items//[]) end' >"\$td/part_\$i.json" 2>/dev/null || true
      # Remove empty arrays to save disk
      jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
      i=\$((i+1))
    done
    merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
    rm -rf "\$td"
  fi
}

ead() {
  local n=\$1 c=\$2; local o="\$OUTPUT_DIR/\$n.json"; echo -n "  \$n (per-AD)..."
  local td; td=\$(mktemp -d); local i=0
  for cid in "\${CIDS[@]}"; do
    local ads; ads=\$(oci iam availability-domain list --compartment-id "\$cid" \$RF 2>/dev/null|jq -r '.data[]?.name//empty' 2>/dev/null||true)
    [ -z "\$ads" ] && continue
    while IFS= read -r ad; do [ -z "\$ad" ]&&continue
      eval "\$c --compartment-id \$cid --availability-domain \\"\$ad\\" --all \$RF" 2>/dev/null | jq '.data | if type=="array" then . else (.items//[]) end' >"\$td/part_\$i.json" 2>/dev/null || true
      jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
      i=\$((i+1))
    done <<<"\$ads"
  done
  merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
  rm -rf "\$td"
}

epp() {
  local n=\$1 c=\$2 pf=\$3 pk=\$4; local o="\$OUTPUT_DIR/\$n.json" pp="\$OUTPUT_DIR/\$pf.json"; echo -n "  \$n (per-parent)..."
  [ ! -f "\$pp" ] && { echo " skip (no \$pf)"; return; }
  local pids; pids=\$(jq -r "(.data | if type==\\"array\\" then . else (.items//[]) end)[]?\$pk//empty" "\$pp" 2>/dev/null||true)
  [ -z "\$pids" ] && { echo " empty"; return; }
  local td; td=\$(mktemp -d); local i=0
  while IFS= read -r pid; do [ -z "\$pid" ]&&continue
    eval "\$c \$pid --all \$RF" 2>/dev/null | jq '.data | if type=="array" then . else (.items//[]) end' >"\$td/part_\$i.json" 2>/dev/null || true
    jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
    i=\$((i+1))
  done <<<"\$pids"
  merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
  rm -rf "\$td"
}

epb() {
  local n=\$1 c=\$2; local o="\$OUTPUT_DIR/\$n.json" bp="\$OUTPUT_DIR/buckets.json"; echo -n "  \$n (per-bucket)..."
  [ ! -f "\$bp" ] && { echo " skip (no buckets)"; return; }
  local bkts; bkts=\$(jq -r '(.data | if type=="array" then . else (.items//[]) end)[]? | "\\(.name)\\t\\(.namespace)"' "\$bp" 2>/dev/null||true)
  [ -z "\$bkts" ] && { echo " empty"; return; }
  local td; td=\$(mktemp -d); local i=0
  while IFS=\$'\\t' read -r bn ns; do [ -z "\$bn" ]&&continue
    eval "\$c --bucket-name \\"\$bn\\" -ns \\"\$ns\\" \$RF" 2>/dev/null | jq '.data | if type=="array" then . else if type=="object" then [.] else [] end end' >"\$td/part_\$i.json" 2>/dev/null || true
    jq -e 'length > 0' "\$td/part_\$i.json" >/dev/null 2>&1 || rm -f "\$td/part_\$i.json"
    i=\$((i+1))
  done <<<"\$bkts"
  merge_parts "\$td" "\$o" && echo " OK" || echo " empty"
  rm -rf "\$td"
}

echo "=== IAM ==="
e compartments "oci iam compartment list --compartment-id-in-subtree true"
e users "oci iam user list"
e groups "oci iam group list"
e policies "oci iam policy list"
e dynamic-groups "oci iam dynamic-group list"
epp api-keys "oci iam user api-key list --user-id" users '.id'
epp customer-secret-keys "oci iam customer-secret-key list --user-id" users '.id'
e tag-namespaces "oci iam tag-namespace list"
e tag-defaults "oci iam tag-default list"
epp tags "oci iam tag list --tag-namespace-id" tag-namespaces '.id'
epp auth-tokens "oci iam auth-token list --user-id" users '.id'
epp smtp-credentials "oci iam smtp-credential list --user-id" users '.id'
e network-sources "oci iam network-sources list"
e region-subscriptions "oci iam region-subscription list"

echo "=== Compute ==="
e instances "oci compute instance list"
e images "oci compute image list"
e vnic-attachments "oci compute vnic-attachment list"
ead boot-volume-attachments "oci compute boot-volume-attachment list"
e instance-configurations "oci compute-management instance-configuration list"
e instance-pools "oci compute-management instance-pool list"
e volume-attachments "oci compute volume-attachment list"
e dedicated-vm-hosts "oci compute dedicated-vm-host list"
e capacity-reservations "oci compute compute-capacity-reservation list"
e compute-clusters "oci compute compute-cluster list"
e console-histories "oci compute console-history list"
e autoscaling-configs "oci autoscaling configuration list"

# --- Thorough image collection ---
# Phase 1: Already done above (per-compartment via e())
# Phase 2: Tenancy root compartment — captures platform images not in sub-compartments
# Phase 3: Per-instance backfill — individually fetch any remaining referenced images

# Helper: collect known image OCIDs from images.json into a temp file
_img_known_ids() {
  if [ -f "\$OUTPUT_DIR/images.json" ]; then
    jq -r '(.data | if type=="array" then . else (.items//[]) end)[]?.id//empty' "\$OUTPUT_DIR/images.json" 2>/dev/null | sort -u
  fi
}

# Helper: merge an array of image objects into images.json (deduped by .id)
_img_merge() {
  local src=\$1
  [ ! -s "\$src" ] && return 1
  if [ -f "\$OUTPUT_DIR/images.json" ]; then
    # Merge and deduplicate by .id
    jq -s '.[0].data as \$existing | .[1] as \$new |
      (\$existing | map(.id) | unique) as \$ids |
      (\$new | map(select(.id as \$i | \$ids | index(\$i) | not))) as \$novel |
      .[0] | .data += \$novel
    ' "\$OUTPUT_DIR/images.json" "\$src" >"\$OUTPUT_DIR/images.json.tmp" 2>/dev/null \\
      && mv "\$OUTPUT_DIR/images.json.tmp" "\$OUTPUT_DIR/images.json" && return 0
    rm -f "\$OUTPUT_DIR/images.json.tmp"
    return 1
  else
    jq '{data:.}' "\$src" >"\$OUTPUT_DIR/images.json" 2>/dev/null
  fi
}

# Phase 2: Tenancy root platform images
echo -n "  images (tenancy root)..."
TENANCY_OCID=\$(oci iam compartment list --query 'data[0]."compartment-id"' --raw-output 2>/dev/null || true)
if [ -n "\$TENANCY_OCID" ]; then
  td_root=\$(mktemp -d); root_added=0
  oci compute image list --compartment-id "\$TENANCY_OCID" --all \$RF 2>/dev/null | \\
    jq '.data | if type=="array" then . else (.items//[]) end' >"\$td_root/root_imgs.json" 2>/dev/null || true
  if [ -s "\$td_root/root_imgs.json" ] && jq -e 'length > 0' "\$td_root/root_imgs.json" >/dev/null 2>&1; then
    root_added=\$(jq 'length' "\$td_root/root_imgs.json")
    _img_merge "\$td_root/root_imgs.json" && echo " +\${root_added} (deduped)" || echo " merge failed"
  else
    echo " empty"
  fi
  rm -rf "\$td_root"
else
  echo " skip (could not determine tenancy OCID)"
fi

# Phase 3: Per-instance backfill for any still-missing images
if [ -f "\$OUTPUT_DIR/instances.json" ]; then
  echo -n "  images (per-instance backfill)..."
  td_bf=\$(mktemp -d)

  # Extract unique image OCIDs referenced by instances
  jq -r '
    [(.data | if type=="array" then . else (.items//[]) end)[]
    | [.["image-id"], .["source-details"]?["image-id"]?]
    | map(select(. != null and . != ""))[]]
    | unique[]
  ' "\$OUTPUT_DIR/instances.json" >"\$td_bf/all_ids.txt" 2>/dev/null || true

  # Get known IDs
  _img_known_ids >"\$td_bf/known_ids.txt"

  # Find missing
  sort "\$td_bf/all_ids.txt" >"\$td_bf/all_sorted.txt"
  sort "\$td_bf/known_ids.txt" >"\$td_bf/known_sorted.txt"
  comm -23 "\$td_bf/all_sorted.txt" "\$td_bf/known_sorted.txt" >"\$td_bf/missing.txt"

  missing_count=\$(wc -l < "\$td_bf/missing.txt" | tr -d ' ')
  if [ "\$missing_count" -gt 0 ]; then
    echo -n " \$missing_count missing, fetching..."
    i=0
    while IFS= read -r imgid; do
      [ -z "\$imgid" ] && continue
      oci compute image get --image-id "\$imgid" \$RF 2>/dev/null | jq '.data' >"\$td_bf/img_\$i.json" 2>/dev/null || true
      if [ -s "\$td_bf/img_\$i.json" ] && jq -e '.id' "\$td_bf/img_\$i.json" >/dev/null 2>&1; then
        i=\$((i+1))
      else
        rm -f "\$td_bf/img_\$i.json"
      fi
    done < "\$td_bf/missing.txt"

    if [ \$i -gt 0 ]; then
      jq -s '.' "\$td_bf"/img_*.json >"\$td_bf/backfill.json" 2>/dev/null
      _img_merge "\$td_bf/backfill.json" && echo " +\$i fetched" || echo " merge failed"
    else
      echo " none available (decommissioned)"
    fi
  else
    echo " all accounted for"
  fi
  rm -rf "\$td_bf"
fi

# Report final image count
if [ -f "\$OUTPUT_DIR/images.json" ]; then
  final_count=\$(jq '(.data | if type=="array" then . else (.items//[]) end) | length' "\$OUTPUT_DIR/images.json" 2>/dev/null || echo 0)
  echo "  images total: \$final_count"
fi

echo "=== Network ==="
e vcns "oci network vcn list"
e subnets "oci network subnet list"
e security-lists "oci network security-list list"
e route-tables "oci network route-table list"
e nsgs "oci network nsg list"
e internet-gateways "oci network internet-gateway list"
e nat-gateways "oci network nat-gateway list"
e service-gateways "oci network service-gateway list"
e drgs "oci network drg list"
e drg-attachments "oci network drg-attachment list"
e local-peering-gateways "oci network local-peering-gateway list"
e dhcp-options "oci network dhcp-options list"
e vlans "oci network vlan list"
e cpes "oci network cpe list"
e ipsec-connections "oci network ip-sec-connection list"
e cross-connect-groups "oci network cross-connect-group list"
e cross-connects "oci network cross-connect list"
e virtual-circuits "oci network virtual-circuit list"
e remote-peering-connections "oci network remote-peering-connection list"
e private-ips "oci network private-ip list"
e vtaps "oci network vtap list"
e capture-filters "oci network capture-filter list"
e byoip-ranges "oci network byoip-range list"
e public-ip-pools "oci network public-ip-pool list"
e network-firewalls "oci network-firewall network-firewall list"
e network-firewall-policies "oci network-firewall network-firewall-policy list"
e public-ips "oci network public-ip list --scope REGION"
epp drg-route-tables "oci network drg-route-table list --drg-id" drgs '.id'
epp drg-route-distributions "oci network drg-route-distribution list --drg-id" drgs '.id'

echo "=== Storage ==="
e block-volumes "oci bv volume list"
ead boot-volumes "oci bv boot-volume list"
e volume-backups "oci bv backup list"
e volume-groups "oci bv volume-group list"
ead file-systems "oci fs file-system list"
e buckets "oci os bucket list"
ead mount-targets "oci fs mount-target list"
epb preauth-requests "oci os preauth-request list"
epb lifecycle-policies "oci os object-lifecycle-policy get"
epb replication-policies "oci os replication policy list"

echo "=== Database ==="
e db-systems "oci db system list"
e autonomous-databases "oci db autonomous-database list"
e mysql-db-systems "oci mysql db-system list"
e db-homes "oci db db-home list"
e db-backups "oci db backup list"
e autonomous-db-backups "oci db autonomous-database-backup list"
e autonomous-container-databases "oci db autonomous-container-database list"
epp databases "oci db database list --db-home-id" db-homes '.id'
e pluggable-databases "oci db pluggable-database list"
epp db-nodes "oci db node list --db-system-id" db-systems '.id'
e exadata-infrastructures "oci db exadata-infrastructure list"
e cloud-vm-clusters "oci db cloud-vm-cluster list"
e cloud-exa-infras "oci db cloud-exa-infra list"
e db-software-images "oci db database-software-image list"
e db-key-stores "oci db key-store list"
e maintenance-runs "oci db maintenance-run list"
epp data-guard-associations "oci db data-guard-association list --database-id" databases '.id'
e nosql-tables "oci nosql table list"

echo "=== Database — Managed ==="
e redis-clusters "oci redis redis-cluster list-redis-clusters"
e opensearch-clusters "oci opensearch cluster list"
e psql-db-systems "oci psql db-system-collection list-db-systems"
e psql-backups "oci psql backup-collection list-backups"

echo "=== Load Balancer ==="
e load-balancers "oci lb load-balancer list"
e network-load-balancers "oci nlb network-load-balancer list"

echo "=== Containers ==="
e oke-clusters "oci ce cluster list"
epp node-pools "oci ce node-pool list --cluster-id" oke-clusters '.id'
e container-instances "oci container-instances container-instance list"
e container-repos "oci artifacts container repository list"
e container-images "oci artifacts container image list"
e image-signatures "oci artifacts container image-signature list"

echo "=== Serverless ==="
e functions-applications "oci fn application list"
epp functions "oci fn function list --application-id" functions-applications '.id'
e api-gateways "oci api-gateway gateway list"
epp api-deployments "oci api-gateway deployment list --gateway-id" api-gateways '.id'

echo "=== Security ==="
e vaults "oci kms management vault list"
e secrets "oci vault secret list"
e container-scan-results "oci vulnerability-scanning container-scan-result list"
e waf-policies "oci waf web-app-firewall list"
e bastions "oci bastion bastion list"
e certificates "oci certs-mgmt certificate list"
e cloud-guard-targets "oci cloud-guard target list"
e cloud-guard-detector-recipes "oci cloud-guard detector-recipe list"
e waas-policies "oci waas waas-policy list"
e waas-certificates "oci waas certificate list"
e dr-protection-groups "oci disaster-recovery dr-protection-group list"
e dr-plans "oci disaster-recovery dr-plan list"

echo "=== Observability ==="
e log-groups "oci logging log-group list"
epp logs "oci logging log list --log-group-id" log-groups '.id'
e alarms "oci monitoring alarm list"
e notification-topics "oci ons topic list"
epp notification-subscriptions "oci ons subscription list --topic-id" notification-topics '."topic-id"'
e events-rules "oci events rule list"
e email-senders "oci email sender list"

echo "=== DevOps ==="
e devops-projects "oci devops project list"
epp devops-build-pipelines "oci devops build-pipeline list --project-id" devops-projects '.id'
epp devops-deploy-pipelines "oci devops deploy-pipeline list --project-id" devops-projects '.id'
epp devops-repositories "oci devops repository list --project-id" devops-projects '.id'

echo "=== Messaging ==="
e streams "oci streaming stream list"
e connect-harnesses "oci streaming connect-harness list"
e service-connectors "oci sch service-connector list"
e queues "oci queue queue list"

echo "=== Governance ==="
e resource-manager-stacks "oci resource-manager stack list"
e budgets "oci budgets budget list"
e quotas "oci limits quota list"

echo "=== Health & Monitoring ==="
e health-checks-http "oci health-checks http-monitor list"
e health-checks-ping "oci health-checks ping-monitor list"
e apm-domains "oci apm-control-plane apm-domain list"

echo "=== DNS ==="
e dns-zones "oci dns zone list"
e dns-views "oci dns view list"
e dns-resolvers "oci dns resolver list"
epp dns-resolver-endpoints "oci dns resolver-endpoint list --resolver-id" dns-resolvers '.id'
epp dns-records "oci dns record zone get --zone-name-or-id" dns-zones '.id'
e dns-steering-policies "oci dns steering-policy list"
e dns-steering-policy-attachments "oci dns steering-policy-attachment list"
e dns-tsig-keys "oci dns tsig-key list"

echo ""
echo "Done! ZIP and upload: cd \$OUTPUT_DIR && zip -r ../oci-export.zip *.json"
`;
}
