#!/usr/bin/env bash
# One-shot bootstrap: writes a .env with strong random secrets if one doesn't
# already exist. Safe to re-run — it will never overwrite an existing .env.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  echo "[setup] $ENV_FILE already exists — not touching it."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "[setup] openssl is required to generate secrets. Install it and retry." >&2
  exit 1
fi

JWT_SECRET="$(openssl rand -base64 48 | tr -d '=+/\n' | cut -c1-64)"
POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '=+/\n' | cut -c1-32)"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup.sh. Edit as needed.

# --- App secrets ---
JWT_SECRET=${JWT_SECRET}

# --- Database ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://oci_viz:${POSTGRES_PASSWORD}@postgres:5432/oci_visualizer?connection_limit=20&pool_timeout=30

# --- Server ---
NODE_ENV=production
PORT=4000
HOST=0.0.0.0
LOG_LEVEL=info

# --- TLS ---
# Leave blank to auto-generate a self-signed cert, or set paths to your own.
TLS_ENABLED=true
TLS_CERT=
TLS_KEY=

# --- CORS ---
# Comma-separated origins. Replace with your real frontend URL for remote access.
CORS_ORIGINS=https://localhost:4000

# --- Upload limit (MB) ---
MAX_UPLOAD_SIZE_MB=500
EOF

chmod 600 "$ENV_FILE"

echo "[setup] Wrote $ENV_FILE with random JWT_SECRET and POSTGRES_PASSWORD."
echo "[setup] Next: docker compose up -d --build   (or: npm install && npm run build && npm start)"
